spring:
    application:
        name: fu-ai-code
server:
  port: 48888
  servlet:
      context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.dali.fuaicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
